[package]
name = "taza-toolchain"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bzip2.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
taza-engine = { workspace = true, features = ["lang-hangul"] }
toml.workspace = true
ureq.workspace = true
zip.workspace = true
zstd.workspace = true
