[workspace]
resolver = "3"
members = [
    "crates/taza-engine",
    "crates/taza-toolchain",
    "crates/taza-evaluation",
    "crates/taza-ffi",
]

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
taza-engine = { path = "crates/taza-engine", default-features = false }
taza-toolchain = { path = "crates/taza-toolchain" }
