[package]
name = "taza-packbuild"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
taza-corpus.workspace = true
taza-engine = { workspace = true, features = ["lang-hangul", "lang-japanese"] }
taza-pack.workspace = true
toml.workspace = true
zstd.workspace = true

[dev-dependencies]
flate2.workspace = true
tar.workspace = true
