[package]
name = "taza-ffi"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bindgen.rs"

[dependencies]
taza-core = { path = "../taza-core" }
taza-pack = { path = "../taza-pack" }
uniffi = { version = "0.29", features = ["cli"] }
memmap2 = "0.9"
thiserror = "2"
